# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-27 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Exported', 'Exported'), ('Deleted', 'Deleted')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='community',
            name='type',
            field=models.CharField(choices=[('Open', 'Open'), ('By Request', 'By Request'), ('Invite Only', 'Invite Only')], default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('Concept', 'Concept'), ('In Review', 'In Review'), ('Approved', 'Approved'), ('Completed', 'Completed')], db_index=True, default='Concept', max_length=50),
        ),
        migrations.AlterField(
            model_name='ideacomment',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ideacomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Other comment this is responding to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='central.IdeaComment'),
        ),
    ]
